### ISSUE TITLE
Resolving Issue around File Indexing when Moving files/folders

### ISSUE THREAD

**Issue by danyill** [dadoonet/fscrawler#136]
I found that when I moved a set of files into a folder for fscrawler to go through after it had already been running for several update cycles, it did nothing:

[This](https://github.com/danyill/fscrawler/blob/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java#L314-L316) is a problematic piece of code (see wider context [here](https://github.com/danyill/fscrawler/blob/master/src/main/java/fr/pilato/elasticsearch/crawler/fs/FsCrawlerImpl.java#L311-L322)):

``` java
if (lastScanDate == null || child.lastModifiedDate.isAfter(lastScanDate) || (child.creationDate != null && child.creationDate.isAfter(lastScanDate))) {
  indexFile(stats, child.name, filepath, path.getInputStream(child), child.lastModifiedDate, child.size);
  stats.addFile();
```

Assume:
- fscrawler has already looked across the files at least once
- lastScanDate is therefore populated on the first run
- Files are then copied into a folder which fscrawler should see
- It will not however, because it will assume they have not been modified: lastScanDate will be populated, lastModifiedDate is older than lastScanDate and it is not a newly created file.
- What is required is to also to OR `|| (child.lastChangedDate != null && child.lastChangedDate.isAfter(lastScanDate))` which is what changes when files are moved (at least on Linux and ext4, see below). 

Problem is in the standard Java API the "change" information is not available (see [here](http://stackoverflow.com/questions/16126992/setting-changing-the-ctime-or-change-time-attribute-on-a-file))

So what would be ideal would be:

``` java
 if (lastScanDate == null || child.lastModifiedDate.isAfter(lastScanDate) || (child.creationDate != null && child.creationDate.isAfter(lastScanDate)) || (child.lastChangedDate != null && child.lastChangedDate.isAfter(lastScanDate))) {
   indexFile(stats, child.name, filepath, path.getInputStream(child), child.lastModifiedDate, child.size);
   stats.addFile();
```

So here's what linux does with a file. When a file is made:

``` bash
mulhollandd@magnolia:~/Downloads/random/x$ touch afile
mulhollandd@magnolia:~/Downloads/random/x$ stat afile
  File: ‘afile’
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: fc01h/64513d    Inode: 9708017     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/mulhollandd)   Gid: ( 1000/mulhollandd)
Access: 2015-12-29 19:37:19.163200611 +1300
Modify: 2015-12-29 19:37:19.163200611 +1300
Change: 2015-12-29 19:37:19.163200611 +1300
 Birth: -
```

Note that creation is not filled in. Let's add some random text.

``` bash
mulhollandd@magnolia:~/Downloads/random/x$ nano afile
mulhollandd@magnolia:~/Downloads/random/x$ stat afile
  File: ‘afile’
  Size: 2               Blocks: 8          IO Block: 4096   regular file
Device: fc01h/64513d    Inode: 9708017     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/mulhollandd)   Gid: ( 1000/mulhollandd)
Access: 2015-12-29 19:37:28.863158511 +1300
Modify: 2015-12-29 19:37:29.843154284 +1300
Change: 2015-12-29 19:37:29.843154284 +1300
 Birth: -
```

The Modify and Change fields have been updated.
Now let's try moving the file to another folder:

``` bash
mulhollandd@magnolia:~/Downloads/random/x$ mkdir y
mulhollandd@magnolia:~/Downloads/random/x$ mv afile y
mulhollandd@magnolia:~/Downloads/random/x$ cd y
mulhollandd@magnolia:~/Downloads/random/x/y$ stat afile
  File: ‘afile’
  Size: 2               Blocks: 8          IO Block: 4096   regular file
Device: fc01h/64513d    Inode: 9708017     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/mulhollandd)   Gid: ( 1000/mulhollandd)
Access: 2015-12-29 19:37:28.863158511 +1300
Modify: 2015-12-29 19:37:29.843154284 +1300
Change: 2015-12-29 19:38:02.595015894 +1300
 Birth: -
```

Only the change field has been updated. This is exactly the field which is not available in the standard Java API. This seems like a significant bug or limitation. What to do?

**Comment by rfelker** [comment]
You can reproduce this problem easily:

- All files in a folder were successful indexed into Elasticsearch by fscrawler
- Then you copy a file into this folder with a lastModifiedDate which is older than the lastScanDate
- This file will never be indexed.

First idea of a solution:
fscrawler save the directories into elasticseach in the `_type` folder. I think a solution can be to save the names of the scanned files as a list into that folder `_type`. Each scan must then compare this list of files against that one actually in the folder. With every scan the file list in `_type` folder must be updated.

That's really an overhead but I have no idea how to handle it in another way. Every hint here will be highly appreciated! :+1:

**Comment by dadoonet** [comment]
I added a test with 3de6eb7 which checks that behavior. Apparently the test seems to pass so may be this has been fixed in 2.2 at some point.

**Comment by JohnnyBill** [comment]
It still doesnt work for me (tested on OSX and linux). If i understand correctly, a file is only updated, if the lastModifiedDate changes, but a move wont change the date of the file, but the date of the folders the file was moved from/to. I tested it both with the 2.2 release and master

**Comment by dadoonet** [comment]
Does it mean that the test I wrote is incorrect? I mean that I'm running the tests on OSX so I would expect a failure.

**Comment by JohnnyBill** [comment]
Hi,
i dont know. Anyways, if i move a file, either in OSX finder or via terminal, fscrawler removes the file from the index, the moved file is not reindexed. Unfortunately i dont have the time to investigate further, maybe ill manage to take another look over the weekend.
But thanks for your reply :)

**Comment by dadoonet** [comment]
I see. I'm probably not testing the right thing. I'll check this out. Thanks!

**Comment by stevan1988** [comment]
Hi @dadoonet ,

is this issue resolved on windows 10?

**Comment by dadoonet** [comment]
@stevan1988 To be honest, I'm not testing the project on Windows. I'm unsure.
At some point, I'd expect #399 to solve all that.

**Comment by stevan1988** [comment]
ok, thanks @dadoonet
