### ISSUE TITLE
Windows: deleting a folder containing files, leaves the deleted files in the index

### ISSUE THREAD

**Issue by newschapmj1** [dadoonet/fscrawler#2019]
**Describe the bug**

Simple example to highlight issue
The contents of the file system are only updated in the steps below (no other changes).
Recent build of Fscrawler (Jan 25), Elastic 8.17 all on local machine Windows 11.

Test 1
A/ create 2 indexes for docs and folder
3 files in root folder
1 sub folder "sub1"
3 files added to sub1 folder

B/ Scan 1
Expected 6 docs, 2 folders
Pass found 6 docs, 2 folders (in indexes)
Stop fscrawler
Delete _status.json

C/
Delete sub1 folder (and 3 docs)
Scan 2
Stop fscrawler
Expected 3 docs and 1 folder
Fail - actual 6 docs and 1 folder (in indexes)

**Index** 
3 deleted file values in fscrawler.log not in the index
9                   DEBUG [f.p.e.c.f.FsParserAbstract] Deleting metadata_index_url14/e5e31d6b8fe0ade6ed7f17e347a5fc47
21:56:22,193 DEBUG [f.p.e.c.f.FsParserAbstract] Deleting metadata_index_url14/bc17e3d6273bf1f244faf87e9af250c4
21:56:22,194 DEBUG [f.p.e.c.f.FsParserAbstract] Deleting metadata_index_url14/9e872eb7157a5a2cdf7271d76b558ab7

  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 6,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "metadata_index_url14",
        "_id": "d972177b21673cfba0e2f39cec5e5bfc",
        "_score": 1,
        "_source": {
          "file": {
            "filename": "file1.txt",
            "url": """file://c:\data\folder_url14\file1.txt"""
          }
        }
      },
      {
        "_index": "metadata_index_url14",
        "_id": "e3727b1efe8e3a5325c346c8955d522b",
        "_score": 1,
        "_source": {
          "file": {
            "filename": "file2.txt",
            "url": """file://c:\data\folder_url14\file2.txt"""
          }
        }
      },
      {
        "_index": "metadata_index_url14",
        "_id": "b854ff56b15441a7f6b476247cf97d88",
        "_score": 1,
        "_source": {
          "file": {
            "filename": "file3.txt",
            "url": """file://c:\data\folder_url14\file3.txt"""
          }
        }
      },
      {
        "_index": "metadata_index_url14",
        "_id": "54adc15ac3ace34d4e3eab482c64e10",
        "_score": 1,
        "_source": {
          "file": {
            "filename": "sub1file1.txt",
            "url": """file://c:\data\folder_url14\sub1\sub1file1.txt"""
          }
        }
      },
      {
        "_index": "metadata_index_url14",
        "_id": "e5cc68aebbac7b4fdaa7e61c1819f42",
        "_score": 1,
        "_source": {
          "file": {
            "filename": "sub1file2.txt",
            "url": """file://c:\data\folder_url14\sub1\sub1file2.txt"""
          }
        }
      },
      {
        "_index": "metadata_index_url14",
        "_id": "84f784dd8a7855969d26c467b4f90",
        "_score": 1,
        "_source": {
          "file": {
            "filename": "sub1file3.txt",
            "url": """file://c:\data\folder_url14\sub1\sub1file3.txt"""
          }
        }
      }
    ]
  }
}

**Job Settings**

```yml
name: "metadata_index_url14"
fs:
  url: "c:\\data\\folder_url14"
#  filename_as_id: changed to true
#pathToMetadata: "C:\\FSCrawler_GUID\\guid_mappings_ads.txt"
#BjlAdsName: "bjDocumentLabelXML"
  update_rate: "600m"
  json_support: false
  filename_as_id: false
  add_filesize: true
  remove_deleted: true
  add_as_inner_object: false
  store_source: false
  index_content: true
  indexed_chars: "1"
  attributes_support: true
  raw_metadata: true
  xml_support: false
  index_folders: true
  lang_detect: false
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: false
    pdf_strategy: "ocr_and_text"
  follow_symlinks: true
elasticsearch:
  nodes:
  - url: "https://localhost:9200"

  username: "elastic"
  password: "pFzk94QNP487fuhmZ=ie"
  index: "metadata_index_url14"
  index_folder: "metadata_index_url14_folder"
  bulk_size: 100
  flush_interval: "5s"
  byte_size: "1mb"
  ssl_verification: false
```

**Logs**
fscrawler.log of second scan
```
21:56:14,622 WARN  [f.p.e.c.f.c.FsCrawlerCli] --debug option has been deprecated. Use FS_JAVA_OPTS="-DLOG_LEVEL=debug" instead.
21:56:14,794 DEBUG [f.p.e.c.p.FsCrawlerPluginsManager] Loading plugins
21:56:15,019 ERROR [o.p.AbstractPluginManager] Cannot load plugin 'plugins\fs-local-plugin'
org.pf4j.PluginRuntimeException: There is an already loaded plugin (PluginWrapper [descriptor=PluginDescriptor [pluginId=${project.artifactId}, pluginClass=fr.pilato.elasticsearch.crawler.plugins.welcome.WelcomePlugin, version=${project.version}, provider=${parent.name}, dependencies=[], description=${project.description}, requires=${project.version}, license=Apache License 2.0], pluginPath=plugins\welcome-plugin]) with the same id (${project.artifactId}) as the plugin at path 'plugins\fs-local-plugin'. Simultaneous loading of plugins with the same PluginId is not currently supported.
As a workaround you may include PluginVersion and PluginProvider in PluginId.
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:901) ~[pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139) ~[pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:246) [pf4j-3.13.0.jar:3.13.0]
	at fr.pilato.elasticsearch.crawler.plugins.FsCrawlerPluginsManager.loadPlugins(FsCrawlerPluginsManager.java:41) [classes/:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:137) [classes/:?]
21:56:15,067 ERROR [o.p.AbstractPluginManager] Cannot load plugin 'plugins\fs-s3-plugin'
org.pf4j.PluginRuntimeException: There is an already loaded plugin (PluginWrapper [descriptor=PluginDescriptor [pluginId=${project.artifactId}, pluginClass=fr.pilato.elasticsearch.crawler.plugins.welcome.WelcomePlugin, version=${project.version}, provider=${parent.name}, dependencies=[], description=${project.description}, requires=${project.version}, license=Apache License 2.0], pluginPath=plugins\welcome-plugin]) with the same id (${project.artifactId}) as the plugin at path 'plugins\fs-s3-plugin'. Simultaneous loading of plugins with the same PluginId is not currently supported.
As a workaround you may include PluginVersion and PluginProvider in PluginId.
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:901) ~[pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139) ~[pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:246) [pf4j-3.13.0.jar:3.13.0]
	at fr.pilato.elasticsearch.crawler.plugins.FsCrawlerPluginsManager.loadPlugins(FsCrawlerPluginsManager.java:41) [classes/:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:137) [classes/:?]
21:56:15,086 ERROR [o.p.AbstractPluginManager] Cannot load plugin 'plugins\fs-http-plugin'
org.pf4j.PluginRuntimeException: There is an already loaded plugin (PluginWrapper [descriptor=PluginDescriptor [pluginId=${project.artifactId}, pluginClass=fr.pilato.elasticsearch.crawler.plugins.welcome.WelcomePlugin, version=${project.version}, provider=${parent.name}, dependencies=[], description=${project.description}, requires=${project.version}, license=Apache License 2.0], pluginPath=plugins\welcome-plugin]) with the same id (${project.artifactId}) as the plugin at path 'plugins\fs-http-plugin'. Simultaneous loading of plugins with the same PluginId is not currently supported.
As a workaround you may include PluginVersion and PluginProvider in PluginId.
	at org.pf4j.AbstractPluginManager.loadPluginFromPath(AbstractPluginManager.java:901) ~[pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.DefaultPluginManager.loadPluginFromPath(DefaultPluginManager.java:139) ~[pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:246) [pf4j-3.13.0.jar:3.13.0]
	at fr.pilato.elasticsearch.crawler.plugins.FsCrawlerPluginsManager.loadPlugins(FsCrawlerPluginsManager.java:41) [classes/:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:137) [classes/:?]
21:56:15,176 INFO  [f.p.e.c.f.c.BootstrapChecks] Memory [Free/Total=Percent]: HEAP [220.4mb/4gb=5.38%], RAM [6.3gb/15.9gb=39.9%], Swap [962.8mb/18.8gb=4.98%].
21:56:15,184 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings.json] already exists
21:56:15,185 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] Mapping [6/_settings_folder.json] already exists
21:56:15,185 DEBUG [f.p.e.c.f.c.FsCrawlerCli] Starting job [c:\fscrawler\jobs\metadata_index_url14]...
21:56:16,126 WARN  [f.p.e.c.f.s.Elasticsearch] username is deprecated. Use apiKey instead.
21:56:16,127 WARN  [f.p.e.c.f.s.Elasticsearch] password is deprecated. Use apiKey instead.
21:56:16,132 INFO  [f.p.e.c.f.c.FsCrawlerCli] attributes_support is set to true but getting group is not available on [windows 11].
21:56:16,132 DEBUG [f.p.e.c.p.FsCrawlerPluginsManager] Starting plugins
21:56:16,135 ERROR [o.p.DefaultPluginFactory] fr.pilato.elasticsearch.crawler.plugins.welcome.WelcomePlugin
java.lang.ClassNotFoundException: fr.pilato.elasticsearch.crawler.plugins.welcome.WelcomePlugin
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:169) ~[pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:44) [pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:94) [pf4j-3.13.0.jar:3.13.0]
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:391) [pf4j-3.13.0.jar:3.13.0]
	at fr.pilato.elasticsearch.crawler.plugins.FsCrawlerPluginsManager.startPlugins(FsCrawlerPluginsManager.java:46) [classes/:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.runner(FsCrawlerCli.java:397) [classes/:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:140) [classes/:?]
21:56:16,136 ERROR [o.p.AbstractPluginManager] Unable to start plugin '${project.artifactId}@${project.version}'
java.lang.NullPointerException: Cannot invoke "org.pf4j.Plugin.start()" because the return value of "org.pf4j.PluginWrapper.getPlugin()" is null
	at org.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:391) [pf4j-3.13.0.jar:3.13.0]
	at fr.pilato.elasticsearch.crawler.plugins.FsCrawlerPluginsManager.startPlugins(FsCrawlerPluginsManager.java:46) [classes/:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.runner(FsCrawlerCli.java:397) [classes/:?]
	at fr.pilato.elasticsearch.crawler.fs.cli.FsCrawlerCli.main(FsCrawlerCli.java:140) [classes/:?]
21:56:16,228 DEBUG [f.p.e.c.p.FsCrawlerPluginsManager] Found FsCrawlerExtensionFsProvider extension for type [http]
21:56:16,228 DEBUG [f.p.e.c.p.FsCrawlerPluginsManager] Found FsCrawlerExtensionFsProvider extension for type [local]
21:56:16,228 DEBUG [f.p.e.c.p.FsCrawlerPluginsManager] Found FsCrawlerExtensionFsProvider extension for type [s3]
21:56:16,270 INFO  [f.p.e.c.f.FsCrawlerImpl] attributes_support is set to true but getting group is not available on [windows 11].
21:56:16,277 DEBUG [f.p.e.c.f.FsParserAbstract] creating fs crawler thread [metadata_index_url14] for [c:\data\folder_url14] every [10h]
21:56:16,277 DEBUG [f.p.e.c.f.FsParserAbstract] We are running on Windows without Server settings so we use the separator in accordance with fs.url
21:56:16,279 INFO  [f.p.e.c.f.FsCrawlerImpl] Starting FS crawler
21:56:16,733 WARN  [f.p.e.c.f.c.ElasticsearchClient] We are not doing SSL verification. It's not recommended for production.
21:56:16,843 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version
21:56:19,004 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version returns 8.17.2 and 8 as the major version number
21:56:19,005 INFO  [f.p.e.c.f.c.ElasticsearchClient] Elasticsearch Client connected to a node running version 8.17.2
21:56:19,006 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Semantic search is enabled and we are running on a version of Elasticsearch 8.17.2 which is 8.17 or higher. We will try to use the semantic search features.
21:56:19,007 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get license
21:56:19,015 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get license returns basic
21:56:19,015 WARN  [f.p.e.c.f.c.ElasticsearchClient] Semantic search is enabled but we are running Elasticsearch with a basic license although we need either an enterprise or trial license.We will not be able to use the semantic search features ATM. We might switch later to a vector embeddings generation.
21:56:19,063 DEBUG [f.p.e.c.f.s.FsCrawlerManagementServiceElasticsearchImpl] Elasticsearch Management Service started
21:56:19,073 WARN  [f.p.e.c.f.c.ElasticsearchClient] We are not doing SSL verification. It's not recommended for production.
21:56:19,074 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version
21:56:19,407 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get version returns 8.17.2 and 8 as the major version number
21:56:19,407 INFO  [f.p.e.c.f.c.ElasticsearchClient] Elasticsearch Client connected to a node running version 8.17.2
21:56:19,408 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Semantic search is enabled and we are running on a version of Elasticsearch 8.17.2 which is 8.17 or higher. We will try to use the semantic search features.
21:56:19,408 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get license
21:56:19,414 DEBUG [f.p.e.c.f.c.ElasticsearchClient] get license returns basic
21:56:19,414 WARN  [f.p.e.c.f.c.ElasticsearchClient] Semantic search is enabled but we are running Elasticsearch with a basic license although we need either an enterprise or trial license.We will not be able to use the semantic search features ATM. We might switch later to a vector embeddings generation.
21:56:19,414 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Elasticsearch Document Service started
21:56:19,414 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Creating/updating component templates
21:56:19,430 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_alias]
21:56:19,473 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_settings_shards]
21:56:19,500 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_settings_total_fields]
21:56:19,520 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_mapping_attributes]
21:56:19,544 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_mapping_file]
21:56:19,569 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_mapping_path]
21:56:19,594 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_mapping_attachment]
21:56:19,616 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_mapping_content]
21:56:19,669 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push component template [fscrawler_mapping_meta]
21:56:19,706 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Creating/updating index templates
21:56:19,723 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push index template [fscrawler_docs_metadata_index_url14]
21:56:19,763 DEBUG [f.p.e.c.f.c.ElasticsearchClient] push index template [fscrawler_folders_metadata_index_url14_folder]
21:56:19,785 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler started for [metadata_index_url14] for [c:\data\folder_url14] every [10h]
21:56:19,787 DEBUG [f.p.e.c.f.FsParserAbstract] Fs crawler thread [metadata_index_url14] is now running. Run #1...
21:56:19,795 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14) = \
21:56:19,932 DEBUG [f.p.e.c.f.FsParserAbstract] indexing [c:\data\folder_url14] content
21:56:19,932 DEBUG [f.p.e.c.f.c.f.FileAbstractorFile] Listing local files from c:\data\folder_url14
21:56:19,943 DEBUG [f.p.e.c.f.c.f.FileAbstractorFile] 3 local files found
21:56:19,943 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file1.txt) = \file1.txt
21:56:19,944 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [\file1.txt], includes = [null], excludes = [null]
21:56:19,944 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file1.txt], excludes = [null]
21:56:19,945 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file1.txt], includes = [null]
21:56:19,945 DEBUG [f.p.e.c.f.FsParserAbstract] [\file1.txt] can be indexed: [true]
21:56:19,946 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: \file1.txt
21:56:19,964 DEBUG [f.p.e.c.f.FsParserAbstract] fetching content from [c:\data\folder_url14],[file1.txt]
21:56:19,970 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file1.txt) = \file1.txt
21:56:20,065 INFO  [f.p.e.c.f.t.TikaInstance] OCR is disabled.
21:56:21,697 DEBUG [f.p.e.c.f.t.TikaInstance] We reached the limit we set (1) for file1.txt: Your document contained more than 1 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).
21:56:21,708 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file1.txt) = \file1.txt
21:56:21,757 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Indexing metadata_index_url14/d972177b21673cfba0e2f39cec5e5bfc?pipeline=null
21:56:21,758 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file2.txt) = \file2.txt
21:56:21,758 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [\file2.txt], includes = [null], excludes = [null]
21:56:21,759 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file2.txt], excludes = [null]
21:56:21,759 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file2.txt], includes = [null]
21:56:21,759 DEBUG [f.p.e.c.f.FsParserAbstract] [\file2.txt] can be indexed: [true]
21:56:21,759 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: \file2.txt
21:56:21,784 DEBUG [f.p.e.c.f.FsParserAbstract] fetching content from [c:\data\folder_url14],[file2.txt]
21:56:21,785 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file2.txt) = \file2.txt
21:56:22,036 DEBUG [f.p.e.c.f.t.TikaInstance] We reached the limit we set (1) for file2.txt: Your document contained more than 1 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).
21:56:22,037 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file2.txt) = \file2.txt
21:56:22,053 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Indexing metadata_index_url14/e3727b1efe8e3a5325c346c8955d522b?pipeline=null
21:56:22,059 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file3.txt) = \file3.txt
21:56:22,059 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [\file3.txt], includes = [null], excludes = [null]
21:56:22,059 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file3.txt], excludes = [null]
21:56:22,061 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file3.txt], includes = [null]
21:56:22,061 DEBUG [f.p.e.c.f.FsParserAbstract] [\file3.txt] can be indexed: [true]
21:56:22,061 DEBUG [f.p.e.c.f.FsParserAbstract]   - file: \file3.txt
21:56:22,083 DEBUG [f.p.e.c.f.FsParserAbstract] fetching content from [c:\data\folder_url14],[file3.txt]
21:56:22,085 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file3.txt) = \file3.txt
21:56:22,094 DEBUG [f.p.e.c.f.t.TikaInstance] We reached the limit we set (1) for file3.txt: Your document contained more than 1 characters, and so your requested limit has been reached. To receive the full text of the document, increase your limit. (Text up to the limit is however available).
21:56:22,095 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file3.txt) = \file3.txt
21:56:22,095 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Indexing metadata_index_url14/b854ff56b15441a7f6b476247cf97d88?pipeline=null
21:56:22,096 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed files in [c:\data\folder_url14]...
21:56:22,156 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file1.txt) = \file1.txt
21:56:22,157 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [\file1.txt], includes = [null], excludes = [null]
21:56:22,157 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file1.txt], excludes = [null]
21:56:22,158 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file1.txt], includes = [null]
21:56:22,158 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file2.txt) = \file2.txt
21:56:22,158 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [\file2.txt], includes = [null], excludes = [null]
21:56:22,158 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file2.txt], excludes = [null]
21:56:22,158 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file2.txt], includes = [null]
21:56:22,159 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\file3.txt) = \file3.txt
21:56:22,159 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [false], filename = [\file3.txt], includes = [null], excludes = [null]
21:56:22,159 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file3.txt], excludes = [null]
21:56:22,159 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\file3.txt], includes = [null]
21:56:22,159 DEBUG [f.p.e.c.f.FsParserAbstract] Looking for removed directories in [c:\data\folder_url14]...
21:56:22,172 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] computeVirtualPathName(c:\data\folder_url14, c:\data\folder_url14\c:\data\folder_url14\sub1) = \c:\data\folder_url14\sub1
21:56:22,173 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] directory = [true], filename = [\c:\data\folder_url14\sub1], includes = [null], excludes = [null]
21:56:22,173 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\c:\data\folder_url14\sub1], excludes = [null]
21:56:22,173 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\c:\data\folder_url14\sub1], includes = [null]
21:56:22,173 DEBUG [f.p.e.c.f.f.FsCrawlerUtil] filename = [\c:\data\folder_url14\sub1], excludes = [null]
21:56:22,173 DEBUG [f.p.e.c.f.FsParserAbstract] Delete folder [c:\data\folder_url14\sub1]
21:56:22,189 DEBUG [f.p.e.c.f.FsParserAbstract] Deleting metadata_index_url14/e5e31d6b8fe0ade6ed7f17e347a5fc47
21:56:22,193 DEBUG [f.p.e.c.f.FsParserAbstract] Deleting metadata_index_url14/bc17e3d6273bf1f244faf87e9af250c4
21:56:22,194 DEBUG [f.p.e.c.f.FsParserAbstract] Deleting metadata_index_url14/9e872eb7157a5a2cdf7271d76b558ab7
21:56:22,204 DEBUG [f.p.e.c.f.FsParserAbstract] Deleting metadata_index_url14_folder/c2439097ac153ae3f2b51c1d786ebea
21:56:22,218 DEBUG [f.p.e.c.f.FsParserAbstract] Updating job metadata after run for [metadata_index_url14]: lastrun [2025-02-20T21:56:17.792085400], indexed [3], deleted [0]
21:56:22,219 INFO  [f.p.e.c.f.FsParserAbstract] Closing FS crawler file abstractor [FileAbstractorFile].
21:56:22,219 INFO  [f.p.e.c.f.FsParserAbstract] FS crawler is stopping after 1 run
21:56:22,220 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [metadata_index_url14]
21:56:22,220 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is now stopped
21:56:22,220 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Closing Elasticsearch client manager
21:56:22,223 DEBUG [f.p.e.c.f.f.b.FsCrawlerBulkProcessor] Closing BulkProcessor
21:56:22,224 DEBUG [f.p.e.c.f.f.b.FsCrawlerBulkProcessor] BulkProcessor is now closed
21:56:22,230 DEBUG [f.p.e.c.f.f.b.FsCrawlerBulkProcessor] Executing [5] remaining actions
21:56:22,231 DEBUG [f.p.e.c.f.f.b.FsCrawlerSimpleBulkProcessorListener] Going to execute new bulk composed of 5 actions
21:56:22,286 DEBUG [f.p.e.c.f.c.ElasticsearchEngine] Sending a bulk request of [5] documents to the Elasticsearch service
21:56:22,419 DEBUG [f.p.e.c.f.c.ElasticsearchClient] bulk a ndjson of 747 characters
21:56:22,571 DEBUG [f.p.e.c.f.f.b.FsCrawlerSimpleBulkProcessorListener] Executed bulk composed of 5 actions
21:56:22,590 DEBUG [f.p.e.c.f.s.FsCrawlerManagementServiceElasticsearchImpl] Elasticsearch Management Service stopped
21:56:22,590 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Closing Elasticsearch client manager
21:56:22,590 DEBUG [f.p.e.c.f.f.b.FsCrawlerBulkProcessor] Closing BulkProcessor
21:56:22,590 DEBUG [f.p.e.c.f.f.b.FsCrawlerBulkProcessor] BulkProcessor is now closed
21:56:22,590 DEBUG [f.p.e.c.f.f.b.FsCrawlerBulkProcessor] Executing [3] remaining actions
21:56:22,590 DEBUG [f.p.e.c.f.f.b.FsCrawlerSimpleBulkProcessorListener] Going to execute new bulk composed of 3 actions
21:56:22,597 DEBUG [f.p.e.c.f.c.ElasticsearchEngine] Sending a bulk request of [3] documents to the Elasticsearch service
21:56:22,597 DEBUG [f.p.e.c.f.c.ElasticsearchClient] bulk a ndjson of 2646 characters
21:56:22,790 DEBUG [f.p.e.c.f.f.b.FsCrawlerSimpleBulkProcessorListener] Executed bulk composed of 3 actions
21:56:22,792 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Elasticsearch Document Service stopped
21:56:22,792 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
21:56:22,792 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [metadata_index_url14] stopped
21:56:22,831 DEBUG [f.p.e.c.f.FsCrawlerImpl] Closing FS crawler [metadata_index_url14]
21:56:22,832 DEBUG [f.p.e.c.f.FsCrawlerImpl] FS crawler thread is now stopped
21:56:22,832 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Closing Elasticsearch client manager
21:56:22,832 DEBUG [f.p.e.c.f.s.FsCrawlerManagementServiceElasticsearchImpl] Elasticsearch Management Service stopped
21:56:22,832 DEBUG [f.p.e.c.f.c.ElasticsearchClient] Closing Elasticsearch client manager
21:56:22,832 DEBUG [f.p.e.c.f.s.FsCrawlerDocumentServiceElasticsearchImpl] Elasticsearch Document Service stopped
21:56:22,832 DEBUG [f.p.e.c.f.FsCrawlerImpl] ES Client Manager stopped
21:56:22,832 INFO  [f.p.e.c.f.FsCrawlerImpl] FS crawler [metadata_index_url14] stopped
21:56:22,836 DEBUG [f.p.e.c.p.FsCrawlerPluginsManager] Stopping plugins

```

**Expected behaviour**
Test 1
A/ create 2 indexes for docs and folder
3 files in root folder
1 sub folder "sub1"
3 files added to sub1 folder

B/ Scan 1
Expected 6 docs, 2 folders
Pass found 6 docs, 2 folders (in indexes)
Stop fscrawler
Delete _status.json

C/
Delete sub1 folder (and 3 docs)
Scan 2
Stop fscrawler
Expected 3 docs and 1 folder
Fail - actual 6 docs and 1 folder (in indexes)

**Versions:**
 - OS: [Windows 11]
 - Elastic 8..17
 - FSCrawler build from Jan 25

**Attachment**

If the bug is related to a given file, please share this file, so we can reuse it in tests
to reproduce the problem and may be use it in our integration tests.

**Comment by newschapmj1** [comment]
Windows filing system issue
1 problem disappears when use / instead of \\  (retested with with url: "c:\\data\\folderurl15" and url: "c:/data/folderurl15"
2 ID in index for documents is the same regardless of / or \\
3 ID in index for folders is different for / and \\.  Is this correct?

As it would take several weeks to recrawl all our documents (using forward slash) I hope theres is fix to the above issue.

**Comment by newschapmj1** [comment]
May be related to  #1904

**Comment by newschapmj1** [comment]
If I follow the steps described in the bug, but do not delete _status.json before step2 the bug still occurs (1 folder and 2 files in indexes, rather than expected 1 folder and 1 file)

**Comment by dadoonet** [comment]
Hey.

I can confirm the bug indeed.

When [running the CI on Windows](https://github.com/dadoonet/fscrawler/pull/2136), I saw it as well. So I [have to bypass some tests](https://github.com/dadoonet/fscrawler/pull/2136/files#diff-851a74d96f0c7f0117cda253dc922c81de97089b6641a07380fc812e03325d08R99-R107) until I find the fix:

```java
        if (OsValidator.WINDOWS) {
            // On windows the deletion does not work as expected
            // TODO this needs to be fixed
            logger.warn("On Windows we don't detect properly the recursive removal of directories. So we skip the validation of this test");
            countTestHelper(new ESSearchRequest().withIndex(getCrawlerName()), 7L, currentTestResourceDir);
        } else {
            // We expect to have 4 docs now
            countTestHelper(new ESSearchRequest().withIndex(getCrawlerName()), 4L, currentTestResourceDir);
        }
```

**Comment by dadoonet** [comment]
> Windows filing system issue 
> * 1 problem disappears when use / instead of \ (retested with with url: "c:\\data\\folderurl15" and url: "c:/data/folderurl15" 
> * 2 ID in index for documents is the same regardless of / or \ 
> * 3 ID in index for folders is different for / and \. Is this correct?
> 
> As it would take several weeks to recrawl all our documents (using forward slash) I hope there is fix to the above issue.

Yeah. That's exactly the issue.

**Comment by dadoonet** [comment]
To solve this, I think that the easiest way would be to transform on the fly, any `\\` character to `/` so we are always consistent... 
But may be there's something smarter to do when computing the hashcode...

**Comment by dadoonet** [comment]
I pushed a change with #2198 which hopefully helps to solve the issue. @newschapmj1 if you are still using FSCrawler on Windows, could you confirm?

**Comment by newschapmj1** [comment]
Unfortunately the above changes did not fix the issue (included me doing some testing and wrongly thinking it passed the tests)
I have added https://github.com/dadoonet/fscrawler/pull/2204 which fixes the issue (passes mvn tests and my independent tests).
